site_name: 2020_5AI_Team3

nav:
    - 'Project Charter': 'Project Charter.md'
    - 'Software Requirements Specification Plan': 'SRS.md'
    - 'Software Project Management Plan': 'SPMP.md'
   
    
theme:
    name: readthedocs

