site_name: 2020_5AI_Team3

nav:
  - Part 1:
    - 'Project Charter': 'Project Charter.md'
    - 'Software Requirements Specification Plan': 'SRS.md'
    - 'Software Project Management Plan': 'SPMP.md'
    - 'Business Model Canvas': 'Business Model Canvas.pdf'
    - 'Project Model Canvas': 'Project Model Canvas.pdf'
  - Part 2:
    - 'Release Plan' : 'Release Plan.md'
    - 'Iteration Plan' : 'Iteration Plan.md'
    - 'Memo of Understanding' : 'Memo of Understanding.md'
    - 'Project Success Criteria' : 'Project Success Criteria.md'
    - 'Project Closure Report' : 'Project Closure Report.md'
    - 'Status Report' : 'Status Report.md'
    - 'Architecture, Design and Coding Standards' : 'Architecture, Design and Coding Standards.md'
    - 'Test Plan' : 'Test Plan.md'
    - 'Test Case Specification' : 'Test Case Specification.md'
    - 'User Guide' : 'User Guide.md'
    - 'System Documentation' : 'System Documentation.md'
    - 'PDF Release Plan' : 'Release Plan.pdf'
    - 'PDF Iteration Plan' : 'Iteration Plan.pdf'
    - 'PDF Memo of Understanding' : 'Memo of Understanding.pdf'
    - 'PDF Project Success Criteria' : 'Project Success Criteria.pdf'
    - 'PDF Project Closure Report' : 'Project Closure Report.pdf'
    - 'PDF Status Report' : 'Status Report.pdf'
    - 'PDF Architecture, Design and Coding Standards' : 'Architecture, Design and Coding Standards.pdf'
    - 'PDF Test Plan' : 'Test Plan.pdf'
    - 'PDF Test Case Specification' : 'Test Case Specification.pdf'
    - 'PDF User Guide' : 'User Guide.pdf'
    - 'PDF System Documentation' : 'System Documentation.pdf'

   
theme:
    name: readthedocs

